### PR TITLE
Feature/set up jest

### PR DESCRIPTION
**Pull request by Fourteen98**
### New Features: 
- added jest configurations

### CODE REVIEW

**Comment by Fourteen98** [comment]
closes #18

**Comment by aizjicod** [comment]
Good work so far 🎊 
there's only one thing left and that's merge 💯

**Review by aizjicod — APPROVED** [review]
good job so far 🎊 
the only thing left is merge, congratulations 💯

**Comment by Fourteen98** [comment]
@aizjicod  thank you

**Pull request merged**
